{{- $tag := coalesce .Values.image.tag .Chart.AppVersion -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "httpstat-monitor.fullname" . }}
  labels:
    {{- include "httpstat-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "httpstat-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "httpstat-monitor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "httpstat-monitor.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ $tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
