apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "httpstat-monitor.fullname" . }}
  labels:
    {{- include "httpstat-monitor.labels" . | nindent 4 }}
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "httpstat-monitor.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
